version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: parking-api:latest
    container_name: parking-app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: parking-webserver
    restart: unless-stopped
    tty: true
    ports:
        - "8056:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/conf.d/error_log:/var/log/nginx/error_log
      - ./.docker/nginx/conf.d/access_log:/var/log/nginx/access_log
    networks:
      - app-network
  #Queue Service
  queue:
    image: parking-api:latest
    container_name: parking-queue-worker
    environment:
      QUEUE_CONNECTION: database
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: "php artisan queue:listen --tries=3 --timeout=900"
    networks:
      - app-network
  #Scheduler Service
  scheduler:
    image: parking-api:latest
    container_name: parking-command-scheduler
    environment:
      QUEUE_CONNECTION: database
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: "/usr/local/bin/scheduler.sh"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  redis:
    driver: local
